In [1]:
import pandas as pd
import os

In [6]:
data_path = "../data/raw/Premleg_23_24"

files = os.listdir(data_path)

print("Total files:", len(files))

files[:20]

Total files: 55

['accurate_cross_team.csv',
 'accurate_long_balls_team.csv',
 'accurate_pass_team.csv',
 'big_chance_missed_team.csv',
 'big_chance_team.csv',
 'clean_sheet_team.csv',
 'corner_taken_team.csv',
 'effective_clearance_team.csv',
 'expected_goals_conceded_team.csv',
 'expected_goals_team.csv',
 'fk_foul_lost_team.csv',
 'goals_conceded_team_match.csv',
 'interception_team.csv',
 'ontarget_scoring_att_team.csv',
 'penalty_conceded_team.csv',
 'penalty_won_team.csv',
 'player_accurate_long_balls.csv',
 'player_accurate_passes.csv',
 'player_big_chances_created.csv',
 'player_big_chances_missed.csv']

In [7]:
passes = pd.read_csv(
    os.path.join(data_path, "player_accurate_passes.csv")
)

passes.head()

,Rank,Player,Team,Accurate Passes per 90,Pass Success (%),Minutes,Matches,Country
0,1,Rodri,Manchester City,102.9,92.5,2938,34,ESP
1,2,Lewis Dunk,Brighton and Hove Albion,93.1,92.5,2872,33,ENG
2,3,Ruben Dias,Manchester City,86.4,94.1,2557,30,POR
3,4,Pierre-Emile Højbjerg,Tottenham Hotspur,85.3,88.6,1293,36,DEN
4,5,Jan Paul van Hecke,Brighton and Hove Albion,84.3,92.5,2368,28,NED

In [8]:
print("Dataset shape:", passes.shape)

print("\nColumns:")
print(passes.columns.tolist())

print("\nData types:")
print(passes.dtypes)

Dataset shape: (317, 8)

Columns:
['Rank', 'Player', 'Team', 'Accurate Passes per 90', 'Pass Success (%)', 'Minutes', 'Matches', 'Country']

Data types:
Rank                        int64
Player                     object
Team                       object
Accurate Passes per 90    float64
Pass Success (%)          float64
Minutes                     int64
Matches                     int64
Country                    object
dtype: object

In [9]:
passes.isnull().sum()

Rank                      0
Player                    0
Team                      0
Accurate Passes per 90    0
Pass Success (%)          0
Minutes                   0
Matches                   0
Country                   0
dtype: int64

In [10]:
passes.duplicated().sum()

np.int64(0)

In [11]:
passes.shape

(317, 8)

In [12]:
passes.columns.tolist()

['Rank',
 'Player',
 'Team',
 'Accurate Passes per 90',
 'Pass Success (%)',
 'Minutes',
 'Matches',
 'Country']

In [13]:
master_df = passes.drop(columns=["Rank"]).copy()

master_df.head()

,Player,Team,Accurate Passes per 90,Pass Success (%),Minutes,Matches,Country
0,Rodri,Manchester City,102.9,92.5,2938,34,ESP
1,Lewis Dunk,Brighton and Hove Albion,93.1,92.5,2872,33,ENG
2,Ruben Dias,Manchester City,86.4,94.1,2557,30,POR
3,Pierre-Emile Højbjerg,Tottenham Hotspur,85.3,88.6,1293,36,DEN
4,Jan Paul van Hecke,Brighton and Hove Albion,84.3,92.5,2368,28,NED

In [14]:
master_df.shape

(317, 7)

In [15]:
goals = pd.read_csv(
    os.path.join(data_path, "player_top_scorers.csv")
)

goals.head()

,Rank,Player,Team,Goals,Penalties,Minutes,Matches,Country
0,1,Erling Haaland,Manchester City,27.0,7.0,2556,31,NOR
1,2,Cole Palmer,Chelsea,22.0,9.0,2624,34,ENG
2,3,Alexander Isak,Newcastle United,21.0,5.0,2265,30,SWE
3,4,Ollie Watkins,Aston Villa,19.0,0.0,3221,37,ENG
4,4,Phil Foden,Manchester City,19.0,0.0,2865,35,ENG

In [16]:
goals = goals[
    ["Player", "Team", "Goals", "Penalties"]
]

goals.head()

           Player              Team  Goals  Penalties
0  Erling Haaland   Manchester City   27.0        7.0
1     Cole Palmer           Chelsea   22.0        9.0
2  Alexander Isak  Newcastle United   21.0        5.0
3   Ollie Watkins       Aston Villa   19.0        0.0
4      Phil Foden   Manchester City   19.0        0.0

In [17]:
master_df = master_df.merge(
    goals,
    on=["Player", "Team"],
    how="outer"
)

master_df.head()

,Player,Team,Accurate Passes per 90,Pass Success (%),Minutes,Matches,Country,Goals,Penalties
0,Aaron Wan-Bissaka,Manchester United,34.9,82.9,1781.0,22.0,ENG,NaN,NaN
1,Abdoulaye Doucouré,Everton,23.2,78.5,2637.0,32.0,MLI,7.0,0.0
2,Adam Lallana,Brighton and Hove Albion,47.8,90.0,846.0,25.0,ENG,NaN,NaN
3,Adam Smith,Bournemouth,24.7,77.1,2156.0,28.0,ENG,NaN,NaN
4,Adama Traoré,Fulham,NaN,NaN,NaN,NaN,NaN,2.0,0.0

In [18]:
how="outer"

In [19]:
xg = pd.read_csv(
    os.path.join(data_path, "player_expected_goals.csv")
)

xg.head()

,Rank,Player,Team,Expected Goals (xG),Actual Goals,Minutes,Matches,Country
0,1,Erling Haaland,Manchester City,29.3,27.0,2556,31,NOR
1,2,Mohamed Salah,Liverpool,21.2,18.0,2535,32,EGY
2,3,Alexander Isak,Newcastle United,20.3,21.0,2265,30,SWE
3,4,Dominic Solanke,Bournemouth,19.6,19.0,3331,38,ENG
4,5,Nicolas Jackson,Chelsea,18.6,14.0,2804,35,SEN

In [20]:
xg = xg[
    ["Player", "Team", "Expected Goals (xG)"]
]

master_df = master_df.merge(
    xg,
    on=["Player", "Team"],
    how="outer"
)

master_df.head()

,Player,Team,Accurate Passes per 90,Pass Success (%),Minutes,Matches,Country,Goals,Penalties,Expected Goals (xG)
0,Aaron Hickey,Brentford,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.2
1,Aaron Ramsey,Burnley,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.3
2,Aaron Wan-Bissaka,Manchester United,34.9,82.9,1781.0,22.0,ENG,NaN,NaN,0.1
3,Abdoulaye Doucouré,Everton,23.2,78.5,2637.0,32.0,MLI,7.0,0.0,8.8
4,Adam Lallana,Brighton and Hove Albion,47.8,90.0,846.0,25.0,ENG,NaN,NaN,0.8

In [21]:
ratings = pd.read_csv(
    os.path.join(data_path, "player_player_ratings.csv")
)

ratings.head()

,Rank,Player,Team,FotMob Rating,Player of the Match Awards,Minutes,Matches,Country
0,1,Rodri,Manchester City,8.12,6.0,2938,34,ESP
1,2,Bukayo Saka,Arsenal,7.97,6.0,2933,35,ENG
2,3,Phil Foden,Manchester City,7.83,10.0,2865,35,ENG
3,4,Bruno Fernandes,Manchester United,7.83,7.0,3119,35,POR
4,5,Cole Palmer,Chelsea,7.78,7.0,2624,34,ENG

In [22]:
ratings = ratings[
    [
        "Player",
        "Team",
        "FotMob Rating",
        "Player of the Match Awards"
    ]
]

master_df = master_df.merge(
    ratings,
    on=["Player", "Team"],
    how="outer"
)

master_df.head()

,Player,Team,Accurate Passes per 90,Pass Success (%),Minutes,Matches,Country,Goals,Penalties,Expected Goals (xG),FotMob Rating,Player of the Match Awards
0,Aaron Hickey,Brentford,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.2,NaN,NaN
1,Aaron Ramsey,Burnley,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.3,NaN,NaN
2,Aaron Wan-Bissaka,Manchester United,34.9,82.9,1781.0,22.0,ENG,NaN,NaN,0.1,7.03,1.0
3,Abdoulaye Doucouré,Everton,23.2,78.5,2637.0,32.0,MLI,7.0,0.0,8.8,7.01,0.0
4,Adam Lallana,Brighton and Hove Albion,47.8,90.0,846.0,25.0,ENG,NaN,NaN,0.8,6.29,0.0

In [23]:
print("Players:", master_df.shape[0])
print("Columns:", master_df.shape[1])

master_df.columns.tolist()

Players: 480
Columns: 12

['Player',
 'Team',
 'Accurate Passes per 90',
 'Pass Success (%)',
 'Minutes',
 'Matches',
 'Country',
 'Goals',
 'Penalties',
 'Expected Goals (xG)',
 'FotMob Rating',
 'Player of the Match Awards']

In [24]:
master_df.head()
master_df.shape
master_df.columns.tolist()

['Player',
 'Team',
 'Accurate Passes per 90',
 'Pass Success (%)',
 'Minutes',
 'Matches',
 'Country',
 'Goals',
 'Penalties',
 'Expected Goals (xG)',
 'FotMob Rating',
 'Player of the Match Awards']

## Merge Additional Player Metrics

The dataset contains separate CSV files for different player statistics.  
We will merge the most useful scouting metrics into the master player table using `Player` and `Team` as the common keys.